
### User Signup 
POST http://localhost:5000/register_user HTTP/1.1
content-type: application/json

{
    "username" : "coolguy69",
    "email": "sahil@gmail.com",
    "password": "123456"
}

### User Signin

POST http://localhost:5000/login_user HTTP/1.1
content-type: application/json

{
    "email": "sahil.com",
    "password": "123456"
}